### ISSUE TITLE
Visibility.txt Accuracy

### ISSUE THREAD

**Issue by AB00k** [Kartik-3004/facexformer#10]
I have tired out the the model inference on a small dataset with different head poses and accuracy of visibility was really bad is there anything I might be doing wrong or I'm right about it.
![image](https://github.com/Kartik-3004/facexformer/assets/121571684/f2bb70b9-e758-46a6-8510-d9abd1ba095a)

**Comment by Kartik-3004** [comment]
Hi!
The first landmark is occluded with hair, that's why - 1. Note - 0 is visible and 1 is occluded.
