### ISSUE TITLE
Could you offer a script to reproduce face attribute acc？

### ISSUE THREAD

**Issue by lcj-la** [Kartik-3004/facexformer#17]
This is a great work, but when I reproduced the celeba test set, I couldn't reach 91.77 in the paper, I could only reach 90.04, and I checked the test code. Can you provide your test acc code? Looking forward to your reply. Thank you.

**Comment by Kartik-3004** [comment]
Hi,
Our work is currently under review. We will share all our scripts once our work is published. You can star the repo to stay updated. 

Thanks !
