### ISSUE TITLE
When will the training code be available?

### ISSUE THREAD

**Issue by prokaryote-hgy** [Kartik-3004/facexformer#2]
Great job! I wonder when will the training code be made available?

**Comment by Kartik-3004** [comment]
It will be made available soon. ☺️

**Comment by zimenglan-sysu-512** [comment]
hi @Kartik-3004 will release the training data?

**Comment by Kartik-3004** [comment]
Hi ! 
Yes, the training data as well as the dataloaders will be released.

**Comment by zimenglan-sysu-512** [comment]
hi @Kartik-3004 still has a plan to release the training code and training data?
thanks.

**Comment by Kartik-3004** [comment]
Hi,
We still plan to release the training code and training data. Our work is under submission currently. We will soon make everything public.

**Comment by zimenglan-sysu-512** [comment]
hi @Kartik-3004 
what about the plan to release the training code and training data?

**Comment by Kartik-3004** [comment]
Hi,
Our work is under review and we cannot share the training code before the acceptance of our work. We will make it public as soon as our work is accepted.

**Comment by HeChengHui** [comment]
@Kartik-3004 
thank you for your impressive work! May i know if there is any estimate for release of training code?

**Comment by Kartik-3004** [comment]
Hi,
The training code will be out by march first week.

**Comment by HeChengHui** [comment]
@Kartik-3004 any further ETA on the training code?

**Comment by preetom-saha-arko** [comment]
It is December, and the training code hasn't been released yet, though it was supposed to be released in March.
