### ISSUE TITLE
can lower verson of torch run the demo?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [Kartik-3004/facexformer#4]
hi @Kartik-3004 
can lower verson of torch run the demo? like torch 1.12.1 or 1.10.

**Comment by Kartik-3004** [comment]
Hi!
I haven't tried running it with a lower version of PyTorch. I recommend installing the dependencies based on the environment_facex.yml and requirements.txt files to avoid any conflicts with dependency versions.

**Comment by zimenglan-sysu-512** [comment]
thx
