### ISSUE TITLE
Can you share age/gender/race mapping

### ISSUE THREAD

**Issue by Podidiving** [Kartik-3004/facexformer#5]
:wave:

It'd be super nice if you can share a mapping dictionary from predictions to actual data.
For example age_gender_race task outputs `1` for the race but I have no idea what it means

Thx in advance

**Comment by Kartik-3004** [comment]
Hi,
We shared the mapping in the Appendix of the paper. I am reiterating it here for your convenience.

```python
age: {
    "0": 0-9,
    "1": 10-19,
    "2": 20-29,
    "3": 30-39,
    "4": 40-49,
    "5": 50-59,
    "6": 60-69,
    "7": over 70
}

gender: {
    "0": Male,
    "1": Female
}

race: {
    "0": White,
    "1": Black,
    "2": Indian,
    "3": Asian,
    "4": Others
}
```

**Comment by kochj02** [comment]
Can you put this in the README somewhere?
