### ISSUE TITLE
What do the values in Visibility.txt represent?

### ISSUE THREAD

**Issue by AB00k** [Kartik-3004/facexformer#7]
I'm uncertain about the meaning of each value in visibility.txt and attributes.txt. I'm particularly interested in understanding visibility.txt, as I suspect it's related to landmarks, but I'm unsure how.

**Comment by Kartik-3004** [comment]
Hi,
In visibility.txt you get binary values - 0 or 1, which indicate whether a particular landmark point is visible or not. 0 indicates visible and 1 indicates not visible. Below is the mapping of those 21 landmark points. 
![image](https://github.com/Kartik-3004/facexformer/assets/62802063/617e03e4-9f63-49ca-b0ad-ebddd176a780)

In attributes.txt, you get binary values for the attributes. 1 indicates that a particular attribute is present in the face. The ordering of attributes is same as in CelebA.

**Comment by AB00k** [comment]
But the response that I'm receiving has 29 values in visibility.txt and also I wanna know if there is any relation between landmarks and visibility output from model that we can use like if I want to see which landmark point represents which point in visibility.txt is it possible.

**Comment by Kartik-3004** [comment]
Hi, 
The visibility output predicts the visibility for 29 landmark points, however we don't predict the coordinates for those landmark points but only the visibility. We use the % of visible landmark points as the estimate of the visibility. 

We don't provide a direct prediction of landmark and its visibility. However, if you want the exact mapping of landmark and its visibility, I suggest you to convert the 68 landmarks that are predicted to 29 landmarks using 68 --> 29 landmark mapping, which might be available online (not sure).
