### ISSUE TITLE
Occulusion Aware?

### ISSUE THREAD

**Issue by Oguzhanercan** [Kartik-3004/facexformer#9]
Does the segmentation model is able to segment occlusion?

**Comment by Kartik-3004** [comment]
Hi,
FaceXFormer segmentation module supports occlusion upto some extent as it is trained on CelebAMaskHQ and LaPa datasets which contain occluded samples.

**Comment by Mr-Nobody-dey** [comment]
Although the model is trained with CelebAMaskHQ, it does not perform quite well with masked faces.
